#!/usr/bin/env python3
"""Regenerate MANIFEST.yaml (and optionally INDEX.md) from entry frontmatter.

Usage:
  python scripts/build_manifest.py                 # this repo, manifest only
  python scripts/build_manifest.py --index         # manifest + INDEX.md
  python scripts/build_manifest.py --root <dir> --index   # a project-local .knowledge

MANIFEST.yaml is a machine-readable index (id -> path + retrieval metadata).
INDEX.md is the agent-facing routing table — the ONLY file loaded eagerly;
its content is a pure function of entry content (no timestamps), so
`validate.py --check-index` can detect drift without false positives.
Never edit either by hand — rerun this script after adding or changing entries.
"""
import argparse
import re
import sys
from datetime import date
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from validate import iter_entries, parse_frontmatter, as_date  # noqa: E402

MANIFEST_HEADER = "# AUTO-GENERATED by scripts/build_manifest.py — do not edit by hand.\n"
INDEX_HEADER = ("<!-- GENERATED by scripts/build_manifest.py --index — do not edit by hand. -->\n")
INDEX_LINE_BUDGET = 120
TYPE_ORDER = ["decision", "constraint", "standard", "pattern", "gotcha",
              "runbook", "context", "glossary", "override"]
COMMENT_RE = re.compile(r"<!--.*?-->", re.DOTALL)


def summary_first_sentence(body: str, limit: int = 160) -> str:
    """First sentence of the ## Summary section, for the INDEX routing line."""
    m = re.search(r"^## Summary\b[^\n]*\n(.*?)(?=^## |\Z)", body,
                  re.MULTILINE | re.DOTALL)
    if not m:
        return ""
    text = COMMENT_RE.sub("", m.group(1))
    text = " ".join(text.split())
    if not text or text == "TODO.":
        return ""
    sentence = re.split(r"(?<=[.!?])\s", text, maxsplit=1)[0]
    if len(sentence) > limit:
        sentence = sentence[: limit - 1].rstrip() + "…"
    return sentence


def load_entries(root: Path):
    entries = []
    for path in iter_entries(root):
        fm, body, err = parse_frontmatter(path)
        if err or not isinstance(fm.get("id"), str):
            print(f"skipping {path.relative_to(root).as_posix()}: {err or 'no id'}",
                  file=sys.stderr)
            continue
        last_updated = as_date(fm.get("last_updated"))
        verified_on = as_date(fm.get("verified_on"))
        review_by = as_date(fm.get("review_by"))
        entries.append({
            "id": fm["id"],
            "path": path.relative_to(root).as_posix(),
            "title": fm.get("title"),
            "domain": fm.get("domain"),
            "type": fm.get("type"),
            "status": fm.get("status"),
            "tags": fm.get("tags", []),
            "last_updated": last_updated.isoformat() if last_updated else None,
            "verified_on": verified_on.isoformat() if verified_on else None,
            "review_by": review_by.isoformat() if review_by else None,
            "summary": summary_first_sentence(body),
        })
    entries.sort(key=lambda e: e["id"])
    return entries


def render_index(root: Path) -> str:
    """Render INDEX.md content. Deterministic: depends only on entry content."""
    entries = load_entries(root)
    lines = [INDEX_HEADER.rstrip("\n"), "", "# Knowledge Index", ""]
    lines += [
        "Routing table — load only this file eagerly; read entries just-in-time.",
        "Read/write rules: see `_meta/PROTOCOL.md` in the global tier "
        "(`~/.knowledge/_meta/PROTOCOL.md`).",
        "",
    ]
    if not entries:
        lines += ["_No entries yet. Create one via `scripts/new_entry.py`._", ""]
    known_types = [t for t in TYPE_ORDER
                   if any(e["type"] == t for e in entries)]
    extra_types = sorted({e["type"] for e in entries} - set(TYPE_ORDER)
                         - {None})
    for entry_type in known_types + extra_types:
        lines.append(f"## {entry_type}")
        lines.append("")
        for e in entries:
            if e["type"] != entry_type:
                continue
            desc = e["summary"] or e["title"] or ""
            marker = "" if e["status"] == "active" else f" _({e['status']})_"
            lines.append(f"- [{e['id']}]({e['path']}){marker} — {desc}")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path,
                        default=Path(__file__).resolve().parent.parent)
    parser.add_argument("--index", action="store_true",
                        help="also regenerate INDEX.md")
    args = parser.parse_args()
    root = args.root.resolve()

    entries = load_entries(root)
    manifest_entries = [{k: v for k, v in e.items() if k != "summary"}
                        for e in entries]
    manifest = {
        "generated": date.today().isoformat(),
        "entry_count": len(manifest_entries),
        "entries": manifest_entries,
    }
    out = root / "MANIFEST.yaml"
    out.write_text(MANIFEST_HEADER + yaml.safe_dump(manifest, sort_keys=False,
                                                    allow_unicode=True),
                   encoding="utf-8")
    print(f"Wrote {out} ({len(entries)} entries)")

    if args.index:
        index_text = render_index(root)
        index_path = root / "INDEX.md"
        index_path.write_text(index_text, encoding="utf-8")
        n_lines = index_text.count("\n")
        print(f"Wrote {index_path} ({n_lines} lines)")
        if n_lines > INDEX_LINE_BUDGET:
            print(f"WARNING: INDEX.md is {n_lines} lines "
                  f"(budget {INDEX_LINE_BUDGET}) — time for /curate gc",
                  file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
